#!/bin/bash
#
#
#
DATE=`date +%F-%H-%M`

# Check if we have a first parameter
if [ -z "$1" ]; 
then
  echo ">>> Not enough parameters! <<<"
  exit
fi

# Check that we have a second paramenter
if [ -z "$2" ];
then
  echo ">>> Need a second parameter! <<<"
  exit
fi

# Get absolute path for first parameter
if [[ $1 =~ ^/ ]];
then
    ORIGIN=$1
else
    ORIGIN=$PWD/$1
fi
echo "> backing up from $ORIGIN"

# Put a trailing backslash in base target, if not present
if [[ $2 =~ /$ ]];
then
  BASETARGET=$2
else
  BASETARGET="$2/"
fi

# Get absolute path for second parameter
if [[ $BASETARGET =~ ^/ ]];
then
  TEMPTARGET=$BASETARGET$DATE-incomplete/
  FULLTARGET=$BASETARGET$DATE/
else
  BASETARGET=$PWD/$BASETARGET
  TEMPTARGET=$BASETARGET$DATE-incomplete/
  FULLTARGET=$BASETARGET$DATE/
fi
echo "> backing up to $FULLTARGET"
echo "> (with temporary dir in $TEMPTARGET)"
echo "> BASETARGET $BASETARGET"

LAST_BACKUP=$(ls -lctr $BASETARGET | grep "^d" | grep -v "incomplete$" | tail -n1 | gawk '{print $NF }')
FULL_LAST_BACKUP=$BASETARGET$LAST_BACKUP/

EXCLUDES_FILE="excludes.txt"
EXCLUDES="$BASETARGET$EXCLUDES_FILE"

if [ -z "$LAST_BACKUP" ]; then
  echo "> No previous backup found. Making first backup to $FULLTARGET"
  mkdir -p $TEMPTARGET
  rsync --archive --one-file-system --human-readable \
    --numeric-ids $ORIGIN $TEMPTARGET
  touch $EXCLUDES
elif [ "$FULL_LAST_BACKUP" = "$FULLTARGET" ]; then
  echo "> Resyncing to same backup $FULLTARGET"
  rsync --archive --one-file-system --human-readable \
    --numeric-ids $ORIGIN $FULL_LAST_BACKUP
else
  echo "> incrementing over $FULL_LAST_BACKUP"
  echo "> excluding files in $EXCLUDES"

  mkdir -p $TEMPTARGET
  rsync --archive --one-file-system --hard-links \
    --human-readable --inplace --numeric-ids --delete \
    --delete-excluded --exclude-from=$EXCLUDES \
    --link-dest=$FULL_LAST_BACKUP $ORIGIN $TEMPTARGET 
fi

if [ -e "$TEMPTARGET" ]; then
  mv $TEMPTARGET $FULLTARGET
fi
