#!/bin/bash

COMMAND=`which ufraw-batch`
FLAGS="--silent --wb=camera --black-point=auto --create-id=also --out-type=jpg --out-depth=16"

if [ -z "$COMMAND" ]; then
  echo "ufraw-batch not found!"
  exit
fi

shopt -s nocaseglob

#REGEXP='^(.*)\.(crw|CRW|cr2|CR2)$'
REGEXP='^(.*)\.(crw|cr2)$'

for i in $@; do 
  if [[ "$i" =~ $REGEXP ]]; then
    #filename=${i%.*} 
    filename=${BASH_REMATCH[1]}
    echo "$i -> $filename.JPG"
    $COMMAND $FLAGS --output=$filename.JPG $i
  else
    echo "$i is not raw file"
  fi
done


