#!/bin/bash

CONVERT=`which convert`
REGEXP='^(.*)\.CR2$'

for i in $@; do 
  if [[ "$i" =~ $REGEXP ]]; then
    #filename=${i%.*} 
    filename=${BASH_REMATCH[1]}
    echo "$i -> $filename.JPG"
    $CONVERT $i $filename.JPG
  else
    echo "$i is not raw file"
  fi
done


